Trending tags a.k.a. hot topics
shortlist-digital/agreable-trending-tags-widget-plugin pull request #1
Opened 2017-07-25 13:52 UTC by leonoragilmour

This has no limit / suggestion currently.

2017-07-25 13:56 UTC, leonoragilmour commented
![](https://github.trello.services/images/mini-trello-icon.png) [WIDGET: Trending Tags](https://trello.com/c/rQyFBFOb/225-widget-trending-tags)

2017-07-25 16:57 UTC, ecoad requested changes
Minor tweaks todo - thanks

2017-07-25 16:57 UTC, ecoad commented on widget-loader-acf.php
> +				'name' => 'tags',
The `name` should match the the `key` minus the prefix-y bit (`$key`)

So if your `key` is `widget_trending_tags_tags_manual` then the `name` should be `tags_manual`.

2017-07-25 16:57 UTC, ecoad commented on widget-loader-acf.php
> +				'label' => 'Tags',
Whitespace issue here

2017-07-25 16:57 UTC, ecoad commented on widget-loader-acf.php
> +		'key' => $key . '_advanced_details_tab',
Whitespace: Can you indent the code inside the array please.

2017-07-26 09:28 UTC, ecoad approved these changes
Thanks

2017-07-26 09:28 UTC, merged